### ISSUE TITLE
[Comment] Extend to compare (other) spreadheets?

### ISSUE THREAD

**Issue by Tux** [manwar/Test-Excel#2]
You use Spreadsheet::ParseExcel, and thus limit yourself to old-fashined MS-Excel (.xls)
The interface to the new MS-Excel (.xlsx) is called Spreadsheet::ParseXLSX and  shares the same API, which would make it relatively easy to merge and extend support for both, adding the possibility to compare .xls to .xlsx!

Taking it even one step further, you could try to use my Spreadsheet::Read and support .xls, .xlsx, .csv, .ods and .sq in one go. If you miss functionality, I could then extend my module to feature the new requirements. (Just brainstorming)

**Comment by manwar** [comment]
Really cool advise. I will try to merge it soon.

**Comment by manwar** [comment]
Hi @Tux 

Just to let you know that I have pushed the support for .xlsx using the Spreadsheet::Read distribution.

https://metacpan.org/release/MANWAR/Test-Excel-1.41

Many Thanks.
Best Regards,
Mohammad S Anwar

**Comment by manwar** [comment]
Closing the issue now as it has been resolved long time ago.
